version: '3'

services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - "${port}:3307"
  
  phpmyadmin:
    image: arm64v8/phpmyadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - mysql
