version: '3.4'
services:
  mysql_container:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
